
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 - group: 'env variables'

steps:
- checkout: self

- task: Bash@3
  displayName: "Run Bootstrap script"
  inputs:
    targetType: filePath
    filePath: 'boostrap.sh'
  env:
   EMAIL: $(email)
   HOSTINGERAPIKEY: $(hostingerApiKey)
