trigger:
 branches:
  include:
    - main

 paths:
   include:
     - app/**

pool:
  vmImage: ubuntu-latest

variables:
- group: 'env variables'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Connect to AKS'
  inputs:
    azureSubscription: 'My-ARM-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
        --resource-group $(aksResourceGroup) \
        --name $(aksClusterName) \
        --overwrite-existing 

- task: Bash@3
  displayName: 'Run Bootstrap Script'
  inputs:
    targetType: filePath
    filePath: './deploy-apps.sh'
  env:
    CLUSTERNAME: $(aksClusterName) 