trigger:
 branches:
  include:
   - main

paths:
 exclude:
  - app/** 
pool:
  vmImage: ubuntu-latest

variables:
- group: 'env variables'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Connect to AKS'
  inputs:
    azureSubscription: 'Revolut-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
        --resource-group $(aksResourceGroup) \
        --name $(aksClusterName) \
        --overwrite-existing      

- task: Bash@3
  displayName: 'Run Bootstrap Script'
  inputs:
    targetType: filePath
    filePath: './bootstrap-prod.sh'
  env:
    EMAIL: $(email)
    HOSTINGERAPIKEY: $(hostingerApiKey)
    CLUSTERNAME: $(aksClusterName)